export enum ActionType {
  MOVE_CELL = "move_cell",
  DELETE_CELL = "delete_cell",
  INSERT_CELL_AFTER = "insert_cell_after",
  UPDATE_CELL = "update_cell",
  BUNDLE_START = "bundle_start",
  BUNDLE_COMPLETE = "bundle_complete",
  SIGN_IN = "sign_in",
  SIGN_OUT = "sign_out",
  SIGN_UP = "sign_up",
  LOADING_USER = "loading_user",
  CLEAR_LOADING_USER = "clear_loading_user",
  SAVE_CODEDOC = "save_codedoc",
  LOAD_CODEDOC = "load_codedoc",
  SET_USER_ERROR = "set_user_error",
  CLEAR_USER_ERROR = "clear_user_error",
}
